### ISSUE TITLE
module information is missing

### ISSUE THREAD

**Issue by steveej** [saschagrunert/kmod#1]
I applied this patch
```diff
diff --git a/Makefile b/Makefile
index 69a2744..e31bf1b 100644
--- a/Makefile
+++ b/Makefile
@@ -8,10 +8,12 @@ ifneq "$(VERBOSE)" "1"
 .SILENT:
 endif
 
+KERNEL_DIR ?= /lib/modules/$(shell uname -r)/build
+
 all modules:
        @mkdir -p ${BUILD_DIRECTORY}/src
        cp "Makefile.in" "${BUILD_DIRECTORY}/Makefile"
-       @$(MAKE) -C /lib/modules/$(shell uname -r)/build M=${PWD}/${BUILD_DIRECTORY} modules
+       @$(MAKE) -C $(KERNEL_DIR) M=${PWD}/${BUILD_DIRECTORY} modules
 
 clean:
        cargo clean
```

Then compiled against a local kernel source, which works when I compile native (written in plain C) modules.
The resulitng kernel object misses the information that the `MODULE_` macros are supposed to inject:

```bash
steveej@steveej-laptop> modinfo target/kernel/kmod.ko                     ~/src/steveej/kmod
filename:       /home/steveej/src/steveej/kmod/target/kernel/kmod.ko
depends:        
vermagic:       4.11.0 mod_unload modversions 
```

This is a problem because some functions are only exported when the GPL license is active which is not possible to do as it is now.

**Comment by saschagrunert** [comment]
Thank you very much for contributing! 🙂

**Comment by frol** [comment]
PRs #2, #3, #4 fix all the issues for me. You can give my `master` branch a try: https://github.com/frol/kmod
